# This compose file will boot a elk cluster.
#   elasticsearch will listen on local 9200, and  use /opt/data/elasticsearch for storage.
#   es node can scale out.
#   logstash will liten on local udp 2055.
#   kibana will liten on local 5601.
#   After startup, import the visualization in the kibana-exports.json file.


version: '3'

services:

  elasticsearch:                      #默认服务名称就是域名
    image: elasticsearch
    #    hostname: elasticsearch          # 配置域名
    #    build:
    #      context: elasticsearch/
    volumes:
      # :ro,只读挂载时的快照
      - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk

  logstash:
    image: logstash
    #    build:
    #      context: logstash/
    volumes:
      - ./logstash/config/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
    #      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml:ro
    #      - ./logstash/pipeline:/usr/share/logstash/pipeline:ro
    ports:
      - "5000:5000"
    links:
      - elasticsearch
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
    depends_on:
      - elasticsearch
    #    command: sh -c "sleep 10;logstash"
    #指定配置文件
    command: logstash -f /usr/share/logstash/pipeline/logstash.conf

  kibana:
    image: kibana
    #    build:
    #      context: kibana/
    links:
      - elasticsearch
    volumes:
      - ./kibana/config/:/usr/share/kibana/config:ro
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch

networks:

  elk:
    driver: bridge