# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql:8.0.13                  #  (>= 8.0.1)  character_set_database=utf8mb4
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - /data/var/lib/mysql:/var/lib/mysql
    ports:
      - 3306:3306

  adminer:
    image: adminer
    restart: always
    links:
      - db
    ports:
      - 9080:8080